/aruco_node:
  ros__parameters:
    marker_size: 0.055
    aruco_dictionary_id: DICT_4X4_100 #DICT_ARUCO_ORIGINAL #DICT_4X4_1000
    image_topic: /color/image_raw
    camera_info_topic: /color/camera_info
