# Configuration parameters for the RPLidar A3 node used in the TurtleBot2i
rplidar_node:
  ros__parameters:
    channel_type: serial  # Communication channel type
    serial_port: '/dev/ttyUSB1'  # Serial port for the Lidar
    serial_baudrate: 256000  # Baud rate for serial communication
    frame_id: 'lidar_link'  # Frame ID for the Lidar
    inverted: false  # Invert the Lidar data
    angle_compensate: true  # Enable angle compensation
    scan_mode: 'Sensitivity'  # Scan mode setting
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000  # QoS depth for parameter events
          durability: volatile  # QoS durability
          history: keep_last  # QoS history
          reliability: best_effort  # QoS reliability
