# RTAB-Map Visualization Parameters Configuration
# This YAML file contains the configuration parameters for the RTAB-Map visualization node (rtabmap_viz).
# Each parameter is explained with comments to help understand their usage and purpose.
/rtabmap_viz:
  ros__parameters:
    approx_sync: true # Use approximate synchronization for the input topics. If false, the RGB and depth images and the camera info must have the same timestamp.
    camera_node_name: '' # Name of the camera node. Leave empty to use default.
    diagnostic_updater:
      period: 1.0 # Period for diagnostic updates in seconds.
    frame_id: 'base_footprint' # Frame attached to the mobile base.
    init_cache_path: '' # Path to the initial cache file. Leave empty to disable.
    is_rtabmap_paused: false # Flag to pause RTAB-Map.
    max_odom_update_rate: 10.0 # Maximum rate (Hz) to update odometry.
    odom_frame_id: '' # Frame ID for odometry.
    odom_sensor_sync: false # Adjust image and scan poses relatively to odometry pose for each node added to graph. For example, if an image received at t=1s has been synchronized with a scan at t=1.1s (and our reference stamp is the scan) and the robot is moving forward at 1 m/s, then we will ask TF to know the motion between t=1s and t=1.1s (which would be 0.1 m) for the camera to adjust its local transform (-10 cm) relative to scan frame at scan stamp. This also applies to multi-camera synchronization.
    qos: 0 # qos (Quality of Service) argument should match the published topics QoS (1=RELIABLE, 2=BEST EFFORT). ROS1 was always RELIABLE.
    qos_camera_info: 2 # qos (Quality of Service) argument should match the published topics QoS (1=RELIABLE, 2=BEST EFFORT). ROS1 was always RELIABLE.
    qos_image: 2 # qos (Quality of Service) argument should match the published topics QoS (1=RELIABLE, 2=BEST EFFORT). ROS1 was always RELIABLE.
    qos_odom: 2 # qos (Quality of Service) argument should match the published topics QoS (1=RELIABLE, 2=BEST EFFORT). ROS1 was always RELIABLE.
    qos_overrides:
      /clock:
        subscription:
          depth: 1 # Queue size for /clock subscription.
          durability: volatile # Durability setting for /clock subscription.
          history: keep_last  # History setting for /clock subscription.
          reliability: best_effort # Reliability setting for /clock subscription.
      /parameter_events:
        publisher:
          depth: 1000 # Queue size for /parameter_events publisher.
          durability: volatile # Durability setting for /parameter_events publisher.
          history: keep_last # History setting for /parameter_events publisher.
          reliability: reliable  # Reliability setting for /parameter_events publisher.
    qos_scan: 2 # qos (Quality of Service) argument should match the published topics QoS (1=RELIABLE, 2=BEST EFFORT). ROS1 was always RELIABLE.
    qos_sensor_data: 2 # qos (Quality of Service) argument should match the published topics QoS (1=RELIABLE, 2=BEST EFFORT). ROS1 was always RELIABLE.
    qos_user_data: 2 # qos (Quality of Service) argument should match the published topics QoS (1=RELIABLE, 2=BEST EFFORT). ROS1 was always RELIABLE.
    queue_size: 40 # Queue size for message synchronization.
    rgbd_cameras: 1 # Number of RGB-D cameras.
    rtabmap: 'rtabmap' # Name of the RTAB-Map node.
    subscribe_depth: false # Flag to subscribe to depth images.
    subscribe_info_only: false # Flag to subscribe to camera info only.
    subscribe_odom: true # Flag to subscribe to odometry.
    subscribe_odom_info: true # Flag to subscribe to odometry info.
    subscribe_rgb: false # Flag to subscribe to RGB images.
    subscribe_rgbd: true # Flag to subscribe to RGB-D images.
    subscribe_scan: true # Flag to subscribe to 2D laser scan.
    subscribe_scan_cloud: false # Flag to subscribe to 3D laser scan cloud.
    subscribe_scan_descriptor: false # Flag to subscribe to scan descriptor.
    subscribe_sensor_data: false # Flag to subscribe to sensor data.
    subscribe_stereo: false # Flag to subscribe to stereo images.
    subscribe_user_data: false # Flag to subscribe to user data.
    use_sim_time: false # Use simulation time.
    wait_for_transform: 0.2 # Time to wait for transform in seconds.
