image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [583.53629,   0.     , 267.34223,
           0.     , 577.41161, 221.54661,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.188530, -0.190437, -0.012626, -0.038969, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [597.02557,   0.     , 246.87752,   0.     ,
           0.     , 616.96368, 217.03182,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
